### ISSUE TITLE
Equations in readme are not readable

### ISSUE THREAD

**Issue by vietng322611** [apoorvnandan/tensor.h#1]

**Comment by apoorvnandan** [comment]
Can you post a screenshot please? I checked on diff browsers.
<img width="858" alt="image" src="https://github.com/user-attachments/assets/d2bc7902-8bf7-44fd-8280-3e76f7b20173">

**Comment by vietng322611** [comment]
![Screenshot_20241015_222019_GitHub.jpg](https://github.com/user-attachments/assets/3c9dd6dd-49f7-4b6c-8c60-69a92c5685b1)

This one is straight from github android. Maybe this only happen to phones? Because I have tried using browser and still getting the same result.

**Comment by vtmt-jen** [comment]
It may be because a JS code is not being loaded correctly. I have been using uBO while checking the author's repo, and I noticed that this JS code `https://github.githubassets.com/static/javascripts/mathjax/ui/safe.js` is responsible for loading all the mathematical equations from the original text to the correct form. Evidence of this is that when I use uBO and block this specific script from loading, only the equations break; none of the others are affected.

**Comment by vietng322611** [comment]
> It may be because a JS code is not being loaded correctly. I have been using uBO while checking the author's repo, and I noticed that this JS code `https://github.githubassets.com/static/javascripts/mathjax/ui/safe.js` is responsible for loading all the mathematical equations from the original text to the correct form. Evidence of this is that when I use uBO and block this specific script from loading, only the equations break; none of the others are affected.

Well that's a shame. Guess I'm closing this now.
